name: CI

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [next, qa, main]
        tags: ['v*']

jobs:
    tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
            - uses: actions/checkout@v3
            - uses: conda-incubator/setup-miniconda@v2
              with:
                    auto-update-conda: true
                    channels: conda-forge,defaults
                    mamba-version: "*"
                    environment-file: environment.yml
                    cache-env: true
            - name: install garnet_reduction
              run: |
                    python -m pip install -e .
            - name: run unit tests
              run: |
                    echo "running unit tests"
                    xvfb-run --server-args="-screen 0 1920x1080x24" -a python -m pytest --cov=src --cov-report=xml --cov-report=term-missing
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    slug: neutrons/garnet_reduction
