name: CI

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [next, qa, main]
        tags: ['v*']

jobs:
    linux:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
            - uses: actions/checkout@v3
            - uses: conda-incubator/setup-miniconda@v2
              with:
                    auto-update-conda: true
                    channels: conda-forge,defaults
                    mamba-version: "*"
                    environment-file: environment.yml
                    cache-env: true
            - name: install garnetreduction
              run: |
                    python -m pip install -e .
            - name: run unit tests
              run: |
                    echo "running unit tests"
                    xvfb-run --server-args="-screen 0 1920x1080x24" -a python -m pytest --cov=src --cov-report=xml --cov-report=term-missing
            # - name: upload coverage to codecov
            #   uses: codecov/codecov-action@v3
            #   with:
            #         token: ${{ secrets.CODECOV_TOKEN }}
            #         fail_ci_if_error: true
